version = 0.1

[dev]
[dev.deploy]
region = "us-east-1"
stack_name = "sophia-interview-coach-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-613602869984-us-east-1"
s3_prefix = "sophia-interview-coach"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "EnvironmentName=dev PoolName=sophia-interview-coach-users"
